### ISSUE TITLE
Unable to connect to mirrors.ocf.berkeley.edu:http: [IP: 169.229.200.70 80]

### ISSUE THREAD

**Issue by stevetsh** [csalab-id/kalilinux-docker#3]
I tried to run docker-compose up and keep getting these errors. Do you have other source.list?
This is what you are doing in the Dockerfile and seems to be failing to fetch anything

RUN sed -i "s/http.kali.org/mirrors.ocf.berkeley.edu/g" /etc/apt/sources.list

270.4 E: Failed to fetch http://mirrors.ocf.berkeley.edu/kali/pool/main/c/cups-pk-helper/cups-pk-helper_0.2.6-1%2bb1_amd64.deb  Unable to connect to mirrors.ocf.berkeley.edu:http: [IP: 169.229.200.70 80]
270.4 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
failed to solve: process "/bin/sh -c DEBIAN_FRONTEND=noninteractive apt-get -yq install     xfce4-goodies     kali-linux-large     kali-desktop-xfce &&     apt-get -y full-upgrade" did not complete successfully: exit code: 100

**Comment by redhawkeye** [comment]
To ensure a smooth experience in this environment, follow these steps:

Pull the latest changes by executing the following command:
```
docker-compose pull
```
This will fetch the updated image for the environment.

Once the image is pulled, you can proceed with running the environment using the following command:
```
docker-compose up -d
```
This will start the environment in the background.

I have encountered and resolved similar issues in the early stages of development, so you can trust that this approach is reliable.

If you prefer to build the environment yourself, make sure your network connection is stable and capable of accessing the "mirrors.ocf.berkeley.edu" repository.
